name: Daily Checkin

on:
  schedule:
    - cron: "0 20 * * *" # 每天UTC时间20点，即北京时间凌晨4点
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run checkin script
      env:
        COOKIE: ${{ secrets.COOKIE }}
      run: |
        python checkin.py
